apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui
  labels:
    name: karsajobs-ui
spec:
  selector:
    matchLabels:
      name: karsajobs-ui
  template:
    metadata:
      name: karsajobs-ui
      labels:
        name: karsajobs-ui
    spec:
      containers:
        - name: karsajobs-ui
          image: rizkisetyawan/karsajobs-ui:latest
          ports:
            - containerPort: 8000
          env:
          - name: VUE_APP_BACKEND
            value: http://$(KARSAJOBS_SERVICE_SERVICE_HOST):8080